@startuml
'https://plantuml.com/class-diagram

interface Specification {
  Specification and(Specification other);
  Specification andNot(Specification other);
  Specification or(Specification other);
  Specification orNot(Specification other);
  Specification not();
  boolean isSatisfiedBy(Object candidate);
}

abstract class CompositeSpecification implements Specification {
  Specification and(Specification other);
  Specification andNot(Specification other);
  Specification or(Specification other);
  Specification orNot(Specification other);
  Specification not();
  abstract boolean isSatisfiedBy(Object candidate);
}

class AndSpecification extends CompositeSpecification {
  private Specification leftCondition;
  private Specification rightCondition;

  public isSatisfiedBy(object candidate);
}

class AndNotSpecification extends CompositeSpecification {
  private Specification leftCondition;
  private Specification rightCondition;

  public isSatisfiedBy(object candidate);
}

class OrSpecification extends CompositeSpecification {
  private Specification leftCondition;
  private Specification rightCondition;

  public isSatisfiedBy(object candidate);
}

class OrNotSpecification extends CompositeSpecification {
  private Specification leftCondition;
  private Specification rightCondition;

  public isSatisfiedBy(object candidate);
}

class NotSpecification extends CompositeSpecification {
  private Specification condition;

  public isSatisfiedBy(object candidate);
}


@enduml
